entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"
    http:
      middlewares:
        - gzip-compress@file


api:
  dashboard: false
  insecure: false

providers:
  file:
    filename: /etc/traefik/dynamic.yml
  docker:
    exposedByDefault: false
    network: traefikproxy

certificatesResolvers:
  letsencrypt:
    acme:
      storage: acme.json
      httpChallenge:
        entryPoint: web

tls:
  certificatesResolvers:
    default: letsencrypt
