entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"
    http:
      middlewares:
        - gzip-compress@file
      tls:
        certResolver: myresolver


api:
  dashboard: false
  insecure: false

providers:
  file:
    filename: /etc/traefik/dynamic.yml
  docker:
    exposedByDefault: false
    network: traefikproxy

certificatesResolvers:
  myresolver:
    acme:
      storage: acme.json
      httpChallenge:
        entryPoint: web